version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    container_name: restaurant
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8880:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mijuan79e8@gmail.com
      PGADMIN_DEFAULT_PASSWORD: hola1234
    volumes:
      - ./pgadmin4-data:/var/lib/pgadmin